const inputPersonalInformationArray = [{
  type: 'text',
  name: 'firstName',
  className: 'firstNameInput',
  classNameSymbol: 'firstNameSymbol',
  removeErrorNotNull: true,
  removeErrorLength: false,
  classerrorLength: false,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'firstNameString -required',
  nameOfString: 'Имя:',
},
{
  type: 'text',
  name: 'lastName',
  className: 'lastNameInput',
  classNameSymbol: 'lastNameSymbol',
  removeErrorNotNull: true,
  removeErrorLength: false,
  classerrorLength: false,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'lastNameString -required',
  nameOfString: 'Фамилия:',
},
{
  type: 'email',
  name: 'email',
  className: 'emailInput',
  classNameSymbol: 'emailSymbol',
  removeErrorNotNull: true,
  removeErrorLength: false,
  classerrorLength: false,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'emailString -required',
  nameOfString: 'Email:',
},
{
  type: 'tel',
  name: 'phone',
  className: 'phoneInput',
  classNameSymbol: '',
  removeErrorNotNull: false,
  removeErrorLength: true,
  classerrorLength: true,
  minLength: true,
  maxLength: true,
  placeholder: true,
  onFocus: true,
  classNameOfString: 'phoneString',
  nameOfString: 'Телефон:',
},
{
  type: 'text',
  name: 'address',
  className: 'addressInput',
  classNameSymbol: '',
  removeErrorNotNull: false,
  removeErrorLength: false,
  classerrorLength: false,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'addressString',
  nameOfString: 'Адрес:',
},
{
  type: 'password',
  name: 'passwordNew',
  className: 'passwordNewInput',
  classNameSymbol: 'errorSymbolPasswordNew',
  removeErrorNotNull: true,
  removeErrorLength: true,
  classerrorLength: true,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'passwordNewString -required',
  nameOfString: 'Пароль:',
},
{
  type: 'password',
  name: 'passwordNewRepeat',
  className: 'passwordNewRepeatInput',
  classNameSymbol: 'errorSymbolPasswordNewRepeat',
  removeErrorNotNull: true,
  removeErrorLength: false,
  classerrorLength: false,
  minLength: false,
  maxLength: false,
  placeholder: false,
  onFocus: false,
  classNameOfString: 'passwordNewRepeatString -required',
  nameOfString: 'Повторите пароль:',
}];

export default inputPersonalInformationArray;
